import { readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repositoryRoot = new URL("../", import.meta.url);
const outputDirectory = new URL("dist/src/", repositoryRoot);
const repositoryPath = fileURLToPath(repositoryRoot);

await rm(new URL("dist/", repositoryRoot), {
  force: true,
  recursive: true,
});

const result = await build({
  absWorkingDir: repositoryRoot.pathname,
  bundle: true,
  entryNames: "[name]",
  entryPoints: {
    hook: "src/spike/hook.ts",
    server: "src/server.ts",
  },
  format: "esm",
  legalComments: "external",
  metafile: true,
  minifyWhitespace: true,
  outdir: outputDirectory.pathname,
  platform: "node",
  target: "node22",
});

for (const entry of ["hook.js", "server.js"]) {
  const path = new URL(`dist/src/${entry}`, repositoryRoot);
  const bundled = await readFile(path, "utf8");
  await writeFile(path, bundled.replace(/[ \t]+(?=\r?\n)/g, ""), "utf8");
}

const packageRoots = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const marker = `node_modules${sep}`;
  const markerIndex = input.lastIndexOf(marker);
  if (markerIndex === -1) {
    continue;
  }
  const remainder = input.slice(markerIndex + marker.length).split(sep);
  const packageParts = remainder[0]?.startsWith("@")
    ? remainder.slice(0, 2)
    : remainder.slice(0, 1);
  packageRoots.add(
    join(repositoryPath, input.slice(0, markerIndex), marker, ...packageParts),
  );
}

const notices = [];
for (const packageRoot of [...packageRoots].sort()) {
  const metadata = JSON.parse(
    await readFile(join(packageRoot, "package.json"), "utf8"),
  );
  const licenseFiles = (await readdir(packageRoot))
    .filter((entry) => /^licen[cs]e(?:\.|$)/i.test(entry))
    .sort();
  if (licenseFiles.length === 0) {
    throw new Error(`Bundled dependency has no license file: ${packageRoot}`);
  }
  const license = await readFile(join(packageRoot, licenseFiles[0]), "utf8");
  notices.push(
    `## ${metadata.name} ${metadata.version}\n\n${license.trim()}\n`,
  );
}

await writeFile(
  new URL("THIRD_PARTY_NOTICES.md", repositoryRoot),
  [
    "# Third-party notices",
    "",
    "This file is generated by `npm run bundle` from the dependencies included",
    "in the distributable Codex RLM JavaScript bundles.",
    "",
    ...notices,
  ].join("\n"),
  "utf8",
);
